name: Build

on: push

jobs:
  my-job:
    name: My Job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build something requiring CL.EXE
        run: |
          cmake -G "NMake clean" .
          nmake
      # ...
