name: Build

on: push

jobs:
  my-job:
    name: My Job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build something requiring CL.EXE
        run: |
          cmake -G "NMake clean" .
          nmake
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_UPLOAD_NAME }}
          release_name: ${{ env.APP_UPLOAD_NAME }}
          draft: false
          prerelease: false
      - name : upload apk
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: ${{ env.APP_UPLOAD_NAME }}
          path: ${{ env.APP_UPLOAD }}
